### ISSUE TITLE
How to set background?

### ISSUE THREAD

**Issue by JHudd435** [EricKotato/sddm-slice#13]
How do I set the background? I tried setting the background option to the path of my image, with and without quotes, but the background stays the same color.

theme.conf.user:

```
[General]
font=Roboto
background="/home/user/Pictures/background.png"
bg_mode=aspect
parallax_bg_shift=20
color_bg=#330033
color_main=#dddddd
color_dimmed=#888888
color_contrast=#1f1f1f
manual=false
```

**Comment by QazCetelic** [comment]
Have you tried `image:///home/user/Pictures/background.png`?

**Comment by JHudd435** [comment]
Tried that with and without quotes just now, but doesn't seem to work.

```
General]
font=Roboto
background="image:///home/user/Pictures/background.png"
bg_mode=aspect
parallax_bg_shift=20
color_bg=#330033
color_main=#dddddd
color_dimmed=#888888
color_contrast=#1f1f1f
manual=false
```

**Comment by EricKotato** [comment]
See https://github.com/sddm/sddm/issues/350#issuecomment-162770059. In short, for security reasons SDDM is not allowed to access user home folder, so background should be moved to system-wide path.

**Comment by JHudd435** [comment]
Thanks! That worked!
